### ISSUE TITLE
Support Polylines

### ISSUE THREAD

**Issue by bzuillsmith** [gdsestimating/three-dxf#1]
I believe there is only support for LWPolylines, so we need regular Polylines as well. Dxf-parser's latest version should support them already so it's just a matter of displaying them.

**Comment by openhardwarecoza** [comment]
Great,  i was wondering why i see the polylines when i log dxf from dxf-parser but not seeing it show up.

**Comment by bzuillsmith** [comment]
I just added the LaserWeb logo to the dxf-parser tests gdsestimating/dxf-parser@dc82518e to help test and show the output of a POLYLINE entity after it's been parsed. Should be fairly easy to add support for drawing them with just straight lines, point to point.

**Comment by bzuillsmith** [comment]
Basic polylines are now supported in v0.1.1. @b1ed06a329351c100a48f5c5c5e2aaabbf7f6cdf. You can install via ```bower install three-dxf``` or pull the latest changes from the repo directly.

**Comment by openhardwarecoza** [comment]
Super! Updatng now, thanks
