### ISSUE TITLE
Cannot see anything in Viewer

### ISSUE THREAD

**Issue by katsuya0719** [gdsestimating/three-dxf#10]
I tried to run sample file and uploaded dxf file(api-cw750-details.dxf), but I could not see anything in the viewer as below image. Does anyone know why?
![image](https://cloud.githubusercontent.com/assets/10389953/20371806/3e2800d0-aca2-11e6-9cec-bc56014ca7ec.png)

**Comment by MrBloodyshadow** [comment]
When I tried it some months ago I had some problems with the external resources, try opening the console (F12 in chrome) and check if something went wrong.

**Comment by katsuya0719** [comment]
I checked console but it seems that file imported to function correctly. I have no idea what went wrong.
![image](https://cloud.githubusercontent.com/assets/10389953/20372860/3550a92e-aca9-11e6-9c3c-16a15a7358c3.png)

**Comment by bzuillsmith** [comment]
You probably need to zoom out more (down on the scroll wheel while hovering over the box). I've just committed a change that will automatically find the image for you. Still need to verify it works completely and publish, but will have to do that another day.

**Comment by bzuillsmith** [comment]
Should be fixed now in 0.2.1. Please reopen if you continue to have issues.
