### ISSUE TITLE
运行不起来啊，debug显示有错。

### ISSUE THREAD

**Issue by MaggieFan** [gdsestimating/three-dxf#12]
index.js 中选择文件时有错。怎么解决。

**Comment by bzuillsmith** [comment]
I'm sorry, I'm having trouble translating this so I'm not clear about what you are asking.

**Comment by MaggieFan** [comment]
The resource cannot run.
![1cyewck 8 _ 6k1u kpe ei](https://user-images.githubusercontent.com/29597620/28004920-509563e8-657a-11e7-87aa-5b44b2ab2653.png)

**Comment by openhardwarecoza** [comment]
@MaggieFan - first go read the entirety of http://www.catb.org/esr/faqs/smart-questions.html and then try again... :(

**Comment by bzuillsmith** [comment]
Is that the ellipse.dxf file in the test data folder of dxf-parser? Have you tried the sample dxf file in the sample folder of three-dxf?

**Comment by bzuillsmith** [comment]
I don't believe there was support for ellipse until now. I tested it with the file from dxf-parser's test data and it worked.
