### ISSUE TITLE
Select layers

### ISSUE THREAD

**Issue by Gandelr** [gdsestimating/three-dxf#14]
Hy,
it's possible select layers (example dropdown list)  and color single layer?

**Comment by bzuillsmith** [comment]
No. I haven't had time to build an API for that sort of thing. It mostly just reads a file and displays it as is. However, it might not be that hard to modify the existing code to do what you want. It just isn't something I have time for at the moment. I expect my company will one day come back to the project and we'll fill out more of the features but at the moment it's just something I work on in my free time--of which I've had very little lately.

Pull requests are welcome.
