### ISSUE TITLE
dfx-parser version not found

### ISSUE THREAD

**Issue by dhavald99** [gdsestimating/three-dxf#27]
Hi I tried to use sample. 
but getting error : 
![image](https://user-images.githubusercontent.com/8870887/53466840-95314a00-3a79-11e9-8090-d49719b40ec8.png)
@duncanthrax @vinzentvega 

can anyone  look at this please?

**Comment by bzuillsmith** [comment]
@dhavald99 Sorry, I made some commits recently that I should have put on another branch. I've just pushed some fixes though. Go ahead and pull, install, and try again.

**Comment by bzuillsmith** [comment]
Actually, now that I have that working, I see it's erroring with the sample data provided in the repo... an alternative would be to checkout the tag "v0.3.1" with git so that you go back to the last working sample

**Comment by bzuillsmith** [comment]
I've fixed an issue in the library and updated the sample instructions (there are a couple extra steps now). Feel free to reopen if you have any more trouble with it :)
