### ISSUE TITLE
Error in text location

### ISSUE THREAD

**Issue by Huai-Dc** [gdsestimating/three-dxf#28]
normal：
![image](https://user-images.githubusercontent.com/19547344/53709170-c80c8100-3e71-11e9-82a4-9af2317c2eb2.png)
error：
![image](https://user-images.githubusercontent.com/19547344/53709191-e2def580-3e71-11e9-8177-d2986dbeba84.png)
some text error and i can't fix it.
can you help me fix it or give me some advice. when you are free. thanks!

**Comment by Huai-Dc** [comment]
file url:
https://github.com/Huai-Dc/dxfFile/blob/master/%EF%BC%88%E6%80%BB%E5%9B%BE1%EF%BC%9A500%EF%BC%89%E6%80%BB%E5%9B%BE2018.03.12_t7.dxf

**Comment by Serthys** [comment]
I think #20 solves it.
You can try it yourself by adding the changes listed on the commit on the file [src/index.js on the line 497](https://github.com/gdsestimating/three-dxf/blob/ba3c3195bcd99291419a737966e20d31c4806060/src/index.js#L497), then build it and check again.

**Comment by Huai-Dc** [comment]
it's work thanks.
