### ISSUE TITLE
Needs to figure viewport correctly

### ISSUE THREAD

**Issue by bzuillsmith** [gdsestimating/three-dxf#3]
Last I remember, the viewport assumes it should be pointed at 0,0,0. This is a reasonable guess, but **not always** the case. I think we can parse viewport information and start there, or the dxf header may have some reasonable info for where we should point and what the extents of the cad drawing are.

**Comment by openhardwarecoza** [comment]
In laserweb your library already renders exacly where the dxf says it should be.  Tomorrow i will add the 'environment'  to your scene and send a pull.  Already polished (:

**Comment by bzuillsmith** [comment]
Are you sure your code isn't just repositioning the initial viewport? [These lines here](https://github.com/gdsestimating/three-dxf/blob/master/three-dxf.js#L89-L91) show arbitrary values that I was using when testing. It actually doesn't even start at 0,0,0 which I think I mistakenly committed to the repo when I was working with a file that didn't have entities drawn near 0,0,0.

**Comment by openhardwarecoza** [comment]
I'll check the code in the morning,  but it definitely was overlating right on top of my gcode rendered version.

**Comment by openhardwarecoza** [comment]
Ok, sorry, last night almost asleep, reading this - I totally misinterpreted the request! Sorry!

You were referring to the actual viewport parameter http://help.autodesk.com/view/ACD/2016/ENU/?guid=GUID-2602B0FB-02E4-4B9A-B03C-B1D904753D34 

In Laserweb we rely on just counting the max/min points as we parse our way through to determine a "bounding box" - thats easy to use to adjust the camera.   Although that counts as serious cheating (: - we really want to parse instead.

**Comment by openhardwarecoza** [comment]
Right, so havent added the viewport yet (: But one of the first things I missed in looking at that, was that with the blank view currently in there, I have no idea where I am, where my camera is, or where the object is (visually speaking that is)

So i brought over the helper objects I have in LaserWeb  

![grid](https://cloud.githubusercontent.com/assets/7695323/12223567/b833bfd6-b7e3-11e5-9f5a-cfecb05f232a.png)

https://github.com/openhardwarecoza/three-dxf/commit/6161f8e434eb8f739ec09e1386c0af99a063a29f

Will help a lot going forward (at least to me)

**Comment by openhardwarecoza** [comment]
![another example](https://cloud.githubusercontent.com/assets/7695323/12223580/0dfbd188-b7e4-11e5-8b61-995b3d47a1ce.png)


Another example where i'd have to pan around looking for the object since its quite a way away from the 0,0,0 point in the Y axis

**Comment by bzuillsmith** [comment]
Yeah, having the axes at the origin visible should be helpful for sure.

As for parsing the viewport from the DXF to find the initial viewport in three-dxf... it may be more problematic than it's worth. It seems various programs out there don't export the viewport completely to the ACAD reference specifications.

There are two places to look in the DXF. You can grab the extents of the drawing from the ```HEADER``` section variables ```$EXTMIN``` and ```$EXTMAX```, or you can go into the ```VPORT``` table and look at the first active 2D, front-facing ```VPORT``` entry. Both can be problematic depending on where the file was made and exported. Some programs will set the header variables to good values thus allowing us to fit all in the view initially without problem. But others programs like OnShape will just set them to values like ```-100000000000000000000``` and ```100000000000000000000```. Same thing happens with ```VPORT```. You can end up getting just default values that don't really mean anything.

It may be that we should simply default to ```(0,0,0)``` and eventually implement a function that find the extents.

**Comment by openhardwarecoza** [comment]
I stumbled onto that already.  My go to is sketchup+guitarlist dxf export, and QCAD - and the sketchup files I tried doesnt have viewport

Is there any 'need' for it? Or can I implement the bounding box based viewport (lets not call it view port then to avoid confusion) - by taking max/min points of objects, and centering camera over that?

**Comment by bzuillsmith** [comment]
Yeah, feel free to replace what I put in there with an implementation that finds the extents for us and make a pull request.

**Comment by bzuillsmith** [comment]
I've opted for finding the extents every time and not attempting to read the view port and header information due to the lack of standard handling across the many CAD applications out there. Working in 0.2.1
