### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by stefanbollmann** [gdsestimating/three-dxf#31]
Trying to run the sample I get a redirection error:

 Hit CTRL-C to stop the server
[Sun Aug 11 2019 17:55:39 GMT+0200 (GMT+02:00)] "GET /sample" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[Sun Aug 11 2019 17:55:39 GMT+0200 (GMT+02:00)] "GET /sample/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[Sun Aug 11 2019 17:55:39 GMT+0200 (GMT+02:00)] "GET /sample//" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[Sun Aug 11 2019 17:55:39 GMT+0200 (GMT+02:00)] "GET /sample///" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[Sun Aug 11 2019 17:55:39 GMT+0200 (GMT+02:00)] "GET /sample////" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[Sun Aug 11 2019 17:55:39 GMT+0200 (GMT+02:00)] "GET /sample/////" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[Sun Aug 11 2019 17:55:39 GMT+0200 (GMT+02:00)] "GET /sample//////" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[Sun Aug 11 2019 17:55:39 GMT+0200 (GMT+02:00)] "GET /sample///////" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[Sun Aug 11 2019 17:55:39 GMT+0200 (GMT+02:00)] "GET /sample////////" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[Sun Aug 11 2019 17:55:39 GMT+0200 (GMT+02:00)] "GET /sample/////////" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[Sun Aug 11 2019 17:55:39 GMT+0200 (GMT+02:00)] "GET /sample//////////" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68

**Comment by Serthys** [comment]
See #29.

**Comment by bzuillsmith** [comment]
The directions have been updated to install a version of http-server that does not have this problem.
