### ISSUE TITLE
How to render from plan view to elevation view using three-dxf

### ISSUE THREAD

**Issue by bulkara** [gdsestimating/three-dxf#32]
Three-dxf renders dxf files in plan view. How to change it to elevation view?

**Comment by Serthys** [comment]
I don't think there's support for that right now.
I found a [TODO referencing the controls](https://github.com/gdsestimating/three-dxf/blob/ba3c3195bcd99291419a737966e20d31c4806060/src/index.js#L174) so you can start by trying arround there.
Here's some documentation links to get you started:
[THREE.OrthographicCamera](https://github.com/gdsestimating/three-dxf/blob/ba3c3195bcd99291419a737966e20d31c4806060/src/index.js#L174)
[OrbitControls](https://threejs.org/docs/#examples/en/controls/OrbitControls)

**Comment by bulkara** [comment]
Thanks for your response. It turns out since it is 2d drawing to flip it to elevation, all one has to do is tweak function drawLine a bit as below. This did the trick for me

if(orientation === 'Elevation'){ 
geometry.vertices.push(new THREE.Vector3(vertex.x, vertex.z, 0))
} else {
geometry.vertices.push(new THREE.Vector3(vertex.x, vertex.y, 0))
}

**Comment by bzuillsmith** [comment]
Glad you figured it out. Yeah, the code presumes to be showing a 2D drawing on the XY plane. Orientation must be something custom you added?
