### ISSUE TITLE
Uncaught TypeError: (intermediate value).setFromPoints is not a function

### ISSUE THREAD

**Issue by thedanieljk** [gdsestimating/three-dxf#33]
I am trying to get three-dxf to work on my liferay tomcat server. I believe I have `dxf-parser.js` fully working and I have r79 of `three.min.js` loaded. 

When trying to display a dxf with the line
 `cadCanvas = new window.ThreeDxf.Viewer(dxf,document.getElementById('mainwrap'),400,400,font);` 

I get the error
```
Uncaught TypeError: (intermediate value).setFromPoints is not a function
    at drawArc (index.js?b635:445)
    at drawEntity (index.js?b635:212)
    at new Viewer (index.js?b635:112)
    at three.min.js:387
    at XMLHttpRequest.<anonymous> (three.min.js:385)
```

I was able to get the sample working with the http-server, so I'm not sure why it doesn't work on this server. Is this an issue with the version of `three.min.js` that I'm using?

**Comment by Serthys** [comment]
I checked and threejs r79 is 3 years old so it's quite likely that things changed a bit.

On the sample is running r101.
https://github.com/gdsestimating/three-dxf/blob/ba3c3195bcd99291419a737966e20d31c4806060/sample/package.json#L11

**Comment by thedanieljk** [comment]
The error was definitely related to using an older version of `three.min.js`. I ripped out the portlet that was causing conflicts with newer versions of `three.min.js` so I could switch to r101. 

Everything works great. Thank you again.
