### ISSUE TITLE
Curve i not define - curve = new THREE.QuadraticBezierCurve3 (drawSpline function)

### ISSUE THREAD

**Issue by studioserviziweb** [gdsestimating/three-dxf#34]
Sorry for my English. The problem is generated when the QuadraticBezierCurve3 class is instantiated:

curve = new THREE.QuadraticBezierCurve3 (points [i], points [i + 1], points [i + 2]);

FILE: src / index.js line 354

Use this file [SPLINE3.zip](https://github.com/gdsestimating/three-dxf/files/3674788/SPLINE3.zip)

P.s .: The problem is also highlighted with QuadraticBezierCurve Function

Thank's

**Comment by Serthys** [comment]
Should be solved by adding 
`var curve;`
right after:
https://github.com/gdsestimating/three-dxf/blob/f3727381fa12908bbebea4ce49cf079741205a2a/src/index.js#L348

**Comment by studioserviziweb** [comment]
Thank's
