### ISSUE TITLE
How to calculate lenght polyline

### ISSUE THREAD

**Issue by studioserviziweb** [gdsestimating/three-dxf#38]
How to calculate length of polyline?

Thanks for your help

**Comment by Serthys** [comment]
I think interacting with the three content is out of scope. Here are some links to get you started:

- https://threejs.org

- https://stackoverflow.com/tags/three.js/info

I haven't used it in a while but you can probably get the distance if you get geometry's the vertices array and iterate adding up the distances between points.

**Comment by robpeters-appliednt** [comment]
Thanks, is this referring to adding a measuring tool? That would be a helpful feature and make this more powerful. Something like a similar set of html code at the project https://github.com/yangosoft/simple-dxf-viewer

It would be helpful to have units of nanometer (nm), micrometer (µm), etc.
![image](https://user-images.githubusercontent.com/38111647/91341781-46ac5b00-e797-11ea-9442-aaab6163fcbb.png)

**Comment by bzuillsmith** [comment]
Indeed, this is out of scope of the project. We're focused on just viewing a parsed dxf file.
