### ISSUE TITLE
parser the 'ATTDEF' got a problem

### ISSUE THREAD

**Issue by liuwanfu** [gdsestimating/three-dxf#44]

**Comment by liuwanfu** [comment]
End in the bad place, I want to fix it. Where can i get the source code?

**Comment by Serthys** [comment]
I guess you are looking for [attdef.js](https://github.com/gdsestimating/dxf-parser/blob/master/src/entities/attdef.js) file in the /gdsestimating/dxf-parser project.

**Comment by liuwanfu** [comment]
got it! thinks!
