### ISSUE TITLE
No compatibility with latest versions of Three

### ISSUE THREAD

**Issue by matndev** [gdsestimating/three-dxf#59]
"ERROR in ./node_modules/three-dxf/src/index.js 472:36-47
"export 'Face3' (imported as 'THREE') was not found in 'three'"

during build time

Three.js version : 0.128.0
Three-dxf version : 1.0.1

**Comment by bzuillsmith** [comment]
Ah yes, looks like Face3 was removed. I haven't been using it in an ESM fashion so it wasn't coming up for me.
