### ISSUE TITLE
Support for pdf

### ISSUE THREAD

**Issue by sivayekula** [gdsestimating/three-dxf#60]
Hi
[Website test images LR.pdf](https://github.com/gdsestimating/three-dxf/files/6671701/Website.test.images.LR.pdf)
, I have a pdf file with multiple dxf images. I have attached sample pdf. Please help me how to extract this pdf or any suggestions. Thanks

**Comment by Serthys** [comment]
[google -> extract pdf vector graphics](https://www.google.com/search?q=extract+pdf+vector+graphics)

**Comment by sivayekula** [comment]
I need to get all vector points from pdf without compress using any of javascript. when I upload the pdf

**Comment by bzuillsmith** [comment]
Sorry, this is far outside the scope of this project. You'll need to look for a library specifically designed to extract stuff from PDF, or learn how to parse it out yourself.
