### ISSUE TITLE
i can't run

### ISSUE THREAD

**Issue by flyingmouse0** [gdsestimating/three-dxf#61]
i add all dependencies manually but i can't run it. I tried 10 times. Can someone please send me a full local version of this? Thank you so much. I'm a beginner sorry
![image](https://user-images.githubusercontent.com/87943151/126906721-a958b949-90f3-4542-b053-15b953e1f207.png)

**Comment by Serthys** [comment]
Can you post what have you tried and/or the file you are trying to open?

**Comment by flyingmouse0** [comment]
1. The file is downloaded as a zip and unzipped.
2. The folder opens in visual studio.
3. Visual studio terminal opens and commands are entered in order:
     > npm install
     > npm run build
     > cd sample
     > npm install
4. Open sample/index.html in visual studio and right click "open with live server" and result:


![image](https://user-images.githubusercontent.com/87943151/126930390-5736d0bb-ca96-44db-9b40-5da6c75c3171.png)

**Comment by Serthys** [comment]
I can't reproduce the issue with the same steps (except the visual studio one) currently on master. Can you check the console for errors? You could also try opening the sample file in `sample\data\api-cw750-details.dxf`, maybe that one works.

**Comment by flyingmouse0** [comment]
please watch this video https://drive.google.com/file/d/1BkYbDpi_VMEcgnNf746Y1jd2jhhDeUZp/view?usp=sharing

**Comment by Serthys** [comment]
You can see in the video an error in the command `npm run build`.
Try running `npm i -D webpack-merge` to get the dependency before the build command and then proceed with the rest.

**Comment by flyingmouse0** [comment]
yes it worked. Thank you very much for spending your precious time.
