### ISSUE TITLE
Sample code fails to render image of DXF files?

### ISSUE THREAD

**Issue by eltonlockhart** [gdsestimating/three-dxf#67]
I have just checke out the repository and following the run sample instructions.

On loading a DXF file the page displays the JSON loaded structure but fails to render the DXF objects.

Console shows the following:
``
three-dxf.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at three-dxf.js:1
(anonymous) @ three-dxf.js:1
index.js:59 progress
index.js:60 100
index.js:92 Uncaught TypeError: Cannot read properties of undefined (reading 'Viewer')
    at index.js:92
    at Object.onLoad (three.min.js:6)
    at XMLHttpRequest.<anonymous> (three.min.js:6)
``

**Comment by bzuillsmith** [comment]
Yes, sorry. The code was in a bit of a transition that I should have started on another branch. Can you pull and give it a try now? I believe this is fixed.

**Comment by eltonlockhart** [comment]
Thanks Ben the sample is working now
