### ISSUE TITLE
Disposing WebGL objects

### ISSUE THREAD

**Issue by bercht-a** [gdsestimating/three-dxf#70]
If I use this three-dxf user in angular SPA and have several calls to "new ThreeDxf.Viewer" I get an warning "Too many active WebGL contexts. Oldest context will be lost."
What is the best approach to clean up those webgl objects? should I somehow call dispose() on all three.js objects?

**Comment by bercht-a** [comment]
I found a way to avoid webgl leaks...

When I call dispose() and forceContextLoss() on the renderer, I don't get those leaks:

 this.dxfViewer?.renderer.dispose();
 this.dxfViewer?.renderer.forceContextLoss();

**Comment by bzuillsmith** [comment]
Thanks for sharing your solution. I wasn't finding much on it. Glad you figured it out
